### ISSUE TITLE
error for importing lights.py

### ISSUE THREAD

**Issue by Zeming-LI-Andy** [Arcascope/circadian#21]
Hi sir,

I could not find Class LightSchedule in lights.py.
Could you help me to deal with it?

![error_for_light_py](https://github.com/Arcascope/circadian/assets/118730192/ecc71bcb-7da6-44e0-8e66-b833ad100dcf)

**Comment by ftavella** [comment]
Hello! Sorry for this bug. We have fixed it in our new `circadian` release `v1.0.0`. If you upgrade the package on pip via:
```
pip install --upgrade circadian
```
it should work. Or in a fresh python environment doing `pip install circadian` should fix the error too.

Let me know if it worked!

**Comment by Zeming-LI-Andy** [comment]
It could work now. Thanks so much.

**Comment by Zeming-LI-Andy** [comment]
I found a BUG that LightSchedule could not add continuously 740 times. Otherwise, it will report an error.

![error1](https://github.com/Arcascope/circadian/assets/118730192/6c2ba4bc-f9c4-4915-a757-da0b2ced36c0)
![error2](https://github.com/Arcascope/circadian/assets/118730192/9dc847de-1f9b-42b7-af1b-946252a02774)

**Comment by Zeming-LI-Andy** [comment]
According to the picture, we could see that the `pulse_lux` is not a nonnegative 'float', but it still reports ValueError.

**Comment by ftavella** [comment]
Hi Zeming-LI-Andy, glad you can download from pip now! And thanks for reporting this bug. I'd love to get to the bottom of it. Could you provide the following so we can explore it further?

- I'd love to see the `data` array to double check that the error is not coming from there (if you can't share it, can you reproduce the error without it?)
- Could you copy the full error report? That way we might be able to track down which part is triggering this error

Other things to try:

- Is only that 740 datapoint the problem? If you create a smaller `data` array that contains that 740 datapoint, does it still throw the error?
- Does the code also fail with a `data` array like `data = [[1.0, 1.0], [3.0, 1.0], [5.0, 1.0], ..., [10.0, 1.0]]`?

**Comment by Zeming-LI-Andy** [comment]
Sorry about that it is not your code error.
I found out that this error is due to Python's recursion depth.
I solved this error by setting a bigger value by sys.getrecursionlimit().

**Comment by ftavella** [comment]
If your goal is to simulate a circadian model using that data as your light input you can do something like this:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from circadian.models import Hannay19

data = pd.read_csv('Hannay_data.csv')
time = data['Time'].to_numpy()
light = data['Light'].to_numpy()

model = Hannay19()
trajectory = model(time, input=light)

# plot the light data
plt.figure(1)
plt.plot(data['Time'], data['Light'])
plt.xlabel('Time (h)')
plt.ylabel('Light (lux)')
plt.title('Light data')
# plot the circadian state
plt.figure(2)
x = trajectory.states[:, 0] * np.cos(trajectory.states[:, 1])
plt.plot(time, x)
plt.xlabel('Time (h)')
plt.ylabel('Circadian state (a.u.)')
plt.title('Circadian state')
plt.show()
```
Output:
![fa1fc775-d89c-46bf-ac20-e15ad5897af9](https://github.com/Arcascope/circadian/assets/67392694/15224c44-c3dc-407a-91f2-7d412fe298a2)

![e8bf7248-39d6-4520-ba4e-e03fffc3bd98](https://github.com/Arcascope/circadian/assets/67392694/a879b505-36c0-4632-9c25-0b4f448d61b9)

Let me know if this helps!

**Comment by Zeming-LI-Andy** [comment]
Great, it helps me so much.
Pretty grateful.

**Comment by Zeming-LI-Andy** [comment]
I have another question how did you get the threshold 5π/12 for estimating DLMO?

**Comment by ftavella** [comment]
You're welcome! Happy it worked. 

The 5π/12 threshold comes from assuming that:
- DLMO happens 7 hours before CBT (minimum of x)
- The period of the clock is 24 hours
- Phase is linear on time

Because:

- We know $x = R cos( \psi )$. Therefore, CBT will happen at $\psi = \pi$
- Assuming the period is 24 hours and a linear relationship between time $t$ and phase $\psi$, we have the following: $\psi = \frac{2\pi}{24} t$
- The phase that corresponds to 7 hours before the minimum is given by $\psi_{DLMO} = \frac{2\pi}{24} (t_{CBT} - 7)$ where $t_{CBT}=  \frac{24}{2 \pi} \pi = 12$
- Therefore, $\psi_{DLMO} = \frac{2\pi}{24} (12 - 7) = \frac{5\pi}{12}$

**Comment by Zeming-LI-Andy** [comment]
Thanks for your clear explanation.
I think I don't have other questions now.
Pretty grateful.
